---
# tasks file for puppet
- name: Baixar o pacote do repositorio do Puppet
  get_url:
    url: "https://apt.puppetlabs.com/puppetlabs-release-pc1-{{ ansible_distribution_release }}.deb"
    dest: /tmp/puppet.deb

- name: Instalar o repositorio do Puppet
  apt:
    deb: /tmp/puppet.deb
    state: present

- name: Instalação dos pacotes e dependencias do Puppet
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - openssl
    - ntp
    - puppet-lint
    - puppet
    - puppet-common
