---
# tasks file for jenkins
- name: Garantir que o jdk esteja na maquina
  apt: name=java

- name: Importando chave jenkins
  apt_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: Adicionando  o repo do jenkins 
  apt_repository:
    repo: http://pkg.jenkins-ci.org/debian-stable binary/
    state: present

- name: Instalacao do jenkins
  apt: name=jenkins
