---
# tasks file for rundeck
- name: Download do repositorio
  apt:
    name: http://repo.rundeck.org/latest.rpm
    state: present

- name: Instalacao do rundeck
  apt:
    name: {{ packages }}
    state: present
